/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/teste2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/teste2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.001, -0.372, 0.142]} scale={0.635}>
        <mesh geometry={nodes.wiper.geometry} material={materials.body_plastic} />
        <mesh geometry={nodes.misc.geometry} material={materials['void']} />
        <mesh geometry={nodes.interior.geometry} material={materials.interior} />
        <mesh geometry={nodes.main002.geometry} material={materials.metal} />
        <mesh geometry={nodes.Plane004.geometry} material={materials.metal} />
        <mesh geometry={nodes.Plane002.geometry} material={materials.metal} />
        <mesh geometry={nodes.Plane005.geometry} material={materials.body_plastic} />
        <mesh geometry={nodes.Plane006.geometry} material={materials.body_plastic} />
        <mesh geometry={nodes.main003.geometry} material={materials.glass} />
        <mesh geometry={nodes.plates.geometry} material={materials['Material.015']} />
        <lineSegments geometry={nodes.mesh_1.geometry} material={materials.main_color} />
        <lineSegments geometry={nodes.mesh_1_1.geometry} material={materials.body_plastic} />
        <lineSegments geometry={nodes.mesh_1_2.geometry} material={materials['void']} />
        <lineSegments geometry={nodes.mesh_1_3.geometry} material={materials.metal} />
        <lineSegments geometry={nodes.mesh_1_4.geometry} material={materials.reflective_light} />
        <lineSegments geometry={nodes.mesh_1_5.geometry} material={materials.glass} />
        <lineSegments geometry={nodes.mesh_1_6.geometry} material={materials.light} />
        <lineSegments geometry={nodes.mesh_1_7.geometry} material={materials.chrome} />
        <lineSegments geometry={nodes.mesh_1_8.geometry} material={materials.backlight} />
        <lineSegments geometry={nodes.mesh_1_9.geometry} material={materials.glass_op0} />
        <mesh geometry={nodes.mesh_3.geometry} material={materials.rubber} />
        <mesh geometry={nodes.mesh_3_1.geometry} material={materials.wheel_color} />
        <mesh geometry={nodes.mesh_3_2.geometry} material={materials.hcap1} />
        <mesh geometry={nodes.mesh_3_3.geometry} material={materials.hcap2} />
        <mesh geometry={nodes.mesh_5.geometry} material={materials.brake_disc} />
        <mesh geometry={nodes.mesh_5_1.geometry} material={materials.brake_color} />
        <mesh geometry={nodes.mesh_5_2.geometry} material={materials.metal} />
        <mesh geometry={nodes.mesh_6.geometry} material={materials.rubber} />
        <mesh geometry={nodes.mesh_6_1.geometry} material={materials.wheel_color} />
        <mesh geometry={nodes.mesh_6_2.geometry} material={materials.hcap1} />
        <mesh geometry={nodes.mesh_6_3.geometry} material={materials.hcap2} />
        <mesh geometry={nodes.mesh_7.geometry} material={materials.rubber} />
        <mesh geometry={nodes.mesh_7_1.geometry} material={materials.wheel_color} />
        <mesh geometry={nodes.mesh_7_2.geometry} material={materials.hcap1} />
        <mesh geometry={nodes.mesh_7_3.geometry} material={materials.hcap2} />
        <mesh geometry={nodes.mesh_8.geometry} material={materials.brake_disc} />
        <mesh geometry={nodes.mesh_8_1.geometry} material={materials.brake_color} />
        <mesh geometry={nodes.mesh_9.geometry} material={materials.main_color} />
        <mesh geometry={nodes.mesh_9_1.geometry} material={materials.body_plastic} />
        <mesh geometry={nodes.mesh_9_2.geometry} material={materials.metal} />
        <mesh geometry={nodes.mesh_11.geometry} material={materials.logo1} />
        <mesh geometry={nodes.mesh_11_1.geometry} material={materials.logo2} />
        <mesh geometry={nodes.mesh_17.geometry} material={materials.plastic} />
        <mesh geometry={nodes.mesh_17_1.geometry} material={materials.light} />
        <mesh geometry={nodes.mesh_17_2.geometry} material={materials.chrome} />
        <mesh geometry={nodes.mesh_17_3.geometry} material={materials.glass_op0} />
        <mesh geometry={nodes.mesh_18.geometry} material={materials.rubber} />
        <mesh geometry={nodes.mesh_18_1.geometry} material={materials.wheel_color} />
        <mesh geometry={nodes.mesh_18_2.geometry} material={materials.hcap1} />
        <mesh geometry={nodes.mesh_18_3.geometry} material={materials.hcap2} />
        <mesh geometry={nodes.mesh_19.geometry} material={materials.brake_disc} />
        <mesh geometry={nodes.mesh_19_1.geometry} material={materials.brake_color} />
      </group>
    </group>
  )
}

useGLTF.preload('/teste2.glb')
