/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/ferrari.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ferrari(props) {
  const { nodes, materials } = useGLTF('./models/ferrari.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.629}>
        <mesh geometry={nodes.FLbrake_1.geometry} material={materials['brake_disc.001']} />
        <mesh geometry={nodes.FLbrake_2.geometry} material={materials['brake_color.001']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.629}>
        <mesh geometry={nodes.FLbrake001_1.geometry} material={materials['brake_disc.001']} />
        <mesh geometry={nodes.FLbrake001_2.geometry} material={materials['brake_color.001']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.629}>
        <mesh geometry={nodes.FLwheel_1.geometry} material={materials['rubber.001']} />
        <mesh geometry={nodes.FLwheel_2.geometry} material={materials['wheel_color.001']} />
        <mesh geometry={nodes.FLwheel_3.geometry} material={materials['hcap1.001']} />
        <mesh geometry={nodes.FLwheel_4.geometry} material={materials['hcap2.001']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.629}>
        <mesh geometry={nodes.FLwheel001_1.geometry} material={materials['rubber.001']} />
        <mesh geometry={nodes.FLwheel001_2.geometry} material={materials['wheel_color.001']} />
        <mesh geometry={nodes.FLwheel001_3.geometry} material={materials['hcap1.001']} />
        <mesh geometry={nodes.FLwheel001_4.geometry} material={materials['hcap2.001']} />
      </group>
      <mesh geometry={nodes.interior.geometry} material={materials['interior.001']} rotation={[Math.PI / 2, 0, 0]} scale={1.629} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.629}>
        <mesh geometry={nodes.main_1.geometry} material={materials['main_color.001']} />
        <mesh geometry={nodes.main_2.geometry} material={materials['body_plastic.001']} />
        <mesh geometry={nodes.main_3.geometry} material={materials['void.001']} />
        <mesh geometry={nodes.main_4.geometry} material={materials['metal.001']} />
        <mesh geometry={nodes.main_5.geometry} material={materials['reflective_light.001']} />
        <mesh geometry={nodes.main_6.geometry} material={materials['glass.001']} />
        <mesh geometry={nodes.main_7.geometry} material={materials['light.001']} />
        <mesh geometry={nodes.main_8.geometry} material={materials['chrome.001']} />
        <mesh geometry={nodes.main_9.geometry} material={materials['backlight.001']} />
        <mesh geometry={nodes.main_10.geometry} material={materials['glass_op0.001']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.629}>
        <mesh geometry={nodes.main001_1.geometry} material={materials['main_color.001']} />
        <mesh geometry={nodes.main001_2.geometry} material={materials['body_plastic.001']} />
        <mesh geometry={nodes.main001_3.geometry} material={materials['metal.001']} />
      </group>
      <mesh geometry={nodes.main002.geometry} material={materials['metal.001']} rotation={[Math.PI / 2, 0, 0]} scale={1.629} />
      <mesh geometry={nodes.main003.geometry} material={materials['glass.001']} rotation={[Math.PI / 2, 0, 0]} scale={1.629} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.629}>
        <mesh geometry={nodes.main004_1.geometry} material={materials['plastic.001']} />
        <mesh geometry={nodes.main004_2.geometry} material={materials['light.001']} />
        <mesh geometry={nodes.main004_3.geometry} material={materials['chrome.001']} />
        <mesh geometry={nodes.main004_4.geometry} material={materials['glass_op0.001']} />
      </group>
      <mesh geometry={nodes.misc.geometry} material={materials['void.001']} rotation={[Math.PI / 2, 0, 0]} scale={1.629} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['metal.001']} rotation={[Math.PI / 2, 0, 0]} scale={1.629} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.629}>
        <mesh geometry={nodes.Plane003_1.geometry} material={materials['logo1.001']} />
        <mesh geometry={nodes.Plane003_2.geometry} material={materials['logo2.001']} />
      </group>
      <mesh geometry={nodes.Plane004.geometry} material={materials['metal.001']} rotation={[Math.PI / 2, 0, 0]} scale={1.629} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['body_plastic.001']} rotation={[Math.PI / 2, 0, 0]} scale={1.629} />
      <mesh geometry={nodes.Plane006.geometry} material={materials['body_plastic.001']} rotation={[Math.PI / 2, 0, 0]} scale={1.629} />
      <mesh geometry={nodes.plates.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={1.629} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.629}>
        <mesh geometry={nodes.Rbrakes_1.geometry} material={materials['brake_disc.001']} />
        <mesh geometry={nodes.Rbrakes_2.geometry} material={materials['brake_color.001']} />
        <mesh geometry={nodes.Rbrakes_3.geometry} material={materials['metal.001']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.629}>
        <mesh geometry={nodes.RLwheel_1.geometry} material={materials['rubber.001']} />
        <mesh geometry={nodes.RLwheel_2.geometry} material={materials['wheel_color.001']} />
        <mesh geometry={nodes.RLwheel_3.geometry} material={materials['hcap1.001']} />
        <mesh geometry={nodes.RLwheel_4.geometry} material={materials['hcap2.001']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.629}>
        <mesh geometry={nodes.RRwheel_1.geometry} material={materials['rubber.001']} />
        <mesh geometry={nodes.RRwheel_2.geometry} material={materials['wheel_color.001']} />
        <mesh geometry={nodes.RRwheel_3.geometry} material={materials['hcap1.001']} />
        <mesh geometry={nodes.RRwheel_4.geometry} material={materials['hcap2.001']} />
      </group>
      <mesh geometry={nodes.wiper.geometry} material={materials['body_plastic.001']} rotation={[Math.PI / 2, 0, 0]} scale={1.629} />
    </group>
  )
}

useGLTF.preload('./models/ferrari.glb')
